---
# Source: helm for kubernetes/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juju
  labels:
    app: juju
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: juju
  template:
    metadata:
      labels:
        app: juju
    spec:
      containers:
        - name: juju
          image: docker.io/phengbunath/juju:1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
